services:
  gpu-runner:
    user: "root"
    build: 
      context: .
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
    shm_size: '16gb' # use the host memory capacity
    volumes:
      - ./unit_test:/app/unit_test/:z
      - ./src:/app/src:ro,z
      - ./objectives:/app/objectives:ro,z
      - ./run:/app/run:z
      - ./analysis:/app/analysis:z
      - /storage/leroy:/app/data:z 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${MY_GPU:-0}"]
              capabilities: [gpu]
    environment:
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - no_proxy=${no_proxy:-}

# to run a script :
# docker compose -f docker-compose.server.yaml run -d --rm gpu-runner python [path of the script in the container]

# -d to run it silently